#!/bin/sh

clear
echo "==============================="
echo "           SOC LAB"
echo "==============================="
echo "1) Test 1"
echo "2) Test 2"
echo "3) Test 3"
echo "0) Exit"
echo
printf "Select test: "
read choice

case "$choice" in
  1) /usr/local/bin/test_1.sh ;;
  2) /usr/local/bin/test_2.sh ;;
  3) /usr/local/bin/test_3.sh ;;
  0) exit 0 ;;
  *) echo "Invalid choice"; exit 1 ;;
esac